/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.financemanagement;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author sreeshanth
 */
public class pay extends javax.swing.JFrame {

    String regex = "\\d+";
    String mailid;
    String line,type,inline;
    int amount,bal;
    String sender;
    /**
     * @param 
     * Creates new form pay
     */
    public pay(String line,int balance) {
        bal = balance;
        this.line = line;
        inline = line;
        mailid = line.split(",")[1];
        this.setResizable(false);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("PAY");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField2.setToolTipText("");

        jLabel1.setText("RECEIVERS USERNAME: ");

        jLabel2.setText("AMOUNT : ");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FOOD", "TRAVEL", "STATIONARIES", "CLOTHING", "MOBILE", "MOVIES", "GAMES", "GIFT", "LENDING", "OTHERS" }));

        jLabel3.setText("EXPENSE TYPE: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(459, 459, 459)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addComponent(jTextField1)
                        .addComponent(jTextField2)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(81, 81, 81))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(12, 12, 12)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButton1)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(714, 377));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        sender = jTextField2.getText();
        type = (String) jComboBox1.getSelectedItem();
        try {
            if(!chkuser(sender)){
                JOptionPane.showMessageDialog(null,"Enter a valid user to send money","title",JOptionPane.WARNING_MESSAGE);
                jTextField1.setText("");
                jTextField2.setText("");
                return;
            }
        } catch (IOException ex) {
            Logger.getLogger(pay.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        try{
            amount = Integer.parseInt(jTextField1.getText());
        }
        catch(NumberFormatException r){
            JOptionPane.showMessageDialog(null,"Enter a valid amount","title",JOptionPane.WARNING_MESSAGE);
            jTextField1.setText("");
        }
        
        if(amount>bal || amount<=-1){
            JOptionPane.showMessageDialog(null,"Insufficient Balance or not a valid money","title",JOptionPane.WARNING_MESSAGE);
            jTextField1.setText("");
        }
        else{
            try {
                writedatain();
                writedataout();
            } catch (IOException ex) {
                Logger.getLogger(pay.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(null,"Transaction Successful","title",JOptionPane.INFORMATION_MESSAGE);
            try {
                new mainpage(inline).setVisible(true);
            } catch (IOException ex) {
                Logger.getLogger(pay.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.dispose();
        }
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private boolean chkuser(String uname) throws FileNotFoundException, IOException{
        FileReader reader = new FileReader("UserData.txt");
        BufferedReader bufread;
        bufread = new BufferedReader(reader);
        
        while((line = bufread.readLine())!=null){
            String[] arrOfStr = line.split(",");
            if(uname.equals(arrOfStr[1])){
                return true;
            }
        }
        return false;
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pay("rand",100).setVisible(true);
            }
        });
    }
    public void writedatain() throws FileNotFoundException, IOException{
        bal = bal - amount;
        FileWriter writer2 = new FileWriter("users\\"+mailid+"transactions.csv",true);
        LocalDateTime timenow = LocalDateTime.now();
        DateTimeFormatter myFormatObj = DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss");
        String formattedDate = timenow.format(myFormatObj);
        String[] arrOfStr = formattedDate.split(" ", 2);
        writer2.write(arrOfStr[0]+","+arrOfStr[1]+","+amount+",1,"+bal+","+sender+"\n");
        writer2.close();
        
        writer2 = new FileWriter("users\\"+mailid+"expense.csv",true);
        timenow = LocalDateTime.now();
        myFormatObj = DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss");
        formattedDate = timenow.format(myFormatObj);
        arrOfStr = formattedDate.split(" ", 2);
        writer2.write(arrOfStr[0]+","+arrOfStr[1]+","+amount+","+type+"\n");
        writer2.close();

    }
    
    public void writedataout() throws IOException{
        int balance = 0;
       
        FileReader reader = new FileReader("users//"+sender+"transactions.csv");
        BufferedReader bufread;
        bufread = new BufferedReader(reader);
        bufread.readLine();
        String line2;
        while((line2 = bufread.readLine())!=null){
            balance = Integer.parseInt(line2.split(",")[4]);
        }
        
        balance = balance+amount;
        
        FileWriter writer2 = new FileWriter("users\\"+sender+"transactions.csv",true);
        LocalDateTime timenow = LocalDateTime.now();
        DateTimeFormatter myFormatObj = DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss");
        String formattedDate = timenow.format(myFormatObj);
        String[] arrOfStr = formattedDate.split(" ", 2);
        writer2.write(arrOfStr[0]+","+arrOfStr[1]+","+amount+",0,"+balance+","+mailid+"\n");
        writer2.close();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
